#!/usr/bin/env python3

import subprocess
import shutil
from pathlib import Path
import os

def run(cmds):
    result = None
    for cmd in cmds.splitlines():
        if cmd:
            print(">>>>", cmd.lstrip())
            result = subprocess.run(cmd, shell=True)
    return result


def install_cmd(binary, install_cmd):
    if shutil.which(binary):
        print(f"Check binary: {binary} installed")
    else:
        print("Installing {binary}")
        run(install_cmd)


install_cmd(
    "brew",
    f'/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
)

install_cmd("git", f"brew install git")

install_cmd("gh", f"brew install gh")

run("gh auth login")

Path('rs').mkdir(exist_ok=True)
os.chdir("rs")

for package in ["rs_install", "rseed", "rsjob", "foam", "foamdb", "AlphaSpace2"]:
    print(f">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
    print(f">> R_S Package: {package}")

    if not Path(package).exists():
        run(f"gh repo clone RedesignScience/{package}")

    os.chdir(package)

    run(f"git pull")
    if Path("setup.py").exists():
        run(f"python setup.py develop")

    if package == "foam":
        run("pip install sqlalchemy alembic psycopg2-binary")

    os.chdir('..')

install_cmd("conda", f"brew install conda")

if run("conda env list | grep rs").returncode != 0:
    run("conda create -n rs")

run("conda activate rs")

install_cmd("mamba", f"conda install -y mamba")

run("mamba env update -f rs_install/rs_mac_conda_env.yaml")




